---
- hosts: all
  tasks:
    - name: enable needed features on NXOS devices
      telnet:
        user: cisco
        password: cisco
        login_prompt: "login: "
        prompts:
          - "#"
        command:
          - terminal length 0
          - configure
          - feature ssh
          - feature nxapi
      when: ansible_os == 'nxos'
